Hw05
sas7289/2024-03-otus-spring-shakhoff pull request #5
Opened 2024-05-16 19:19 UTC by sas7289

2024-05-21 14:46 UTC, VladimirMagerov requested changes

2024-05-21 14:46 UTC, VladimirMagerov commented on hw05-jdbc-hard/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                bookId = rs.getLong("book_id");
Получается, сколько будет жанров у одной книги, столько же раз мы будем и заполнять одни и те же поля? Предлагаю реализовать такую логику, при которой мы заполняем поля книги всего один раз, а не вмсте с каждым её жанром.

2024-05-24 06:29 UTC, sas7289 commented on hw05-jdbc-hard/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                bookId = rs.getLong("book_id");
готово

2024-05-28 22:22 UTC, VladimirMagerov approved these changes

2024-06-04 11:25 UTC, merged