Hw06
sas7289/2024-03-otus-spring-shakhoff pull request #6
Opened 2024-06-04 11:39 UTC by sas7289

2024-06-08 23:08 UTC, VladimirMagerov requested changes

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/main/java/ru/otus/hw/services/BookServiceImpl.java
> +        List<Book> all = bookRepository.findAll();
Не очень информативное название переменной, `allBooks` будет лучше

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/main/java/ru/otus/hw/repositories/JpaBookRepository.java
> +public class JpaBookRepository implements BookRepository {
Репозиторий не покрыт тестами.

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/main/java/ru/otus/hw/repositories/JpaCommentRepository.java
> +public class JpaCommentRepository implements CommentRepository {
Репозиторий не покрыт тестами.

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/test/java/ru/otus/hw/repositories/JdbcGenreRepositoryTest.java
> +class JdbcGenreRepositoryTest {
Полагаю, он уже не JDBC, а JPA

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/test/java/ru/otus/hw/services/BookServiceImplTest.java
> +@DataJpaTest
DataJpaTest используется только для теста репозиториев.

Для интеграционного теста лучше использовать `@SpringBootTest`.

2024-06-08 23:08 UTC, VladimirMagerov commented on hw06-jpa/src/test/java/ru/otus/hw/services/CommentServiceImplTest.java
> +@DataJpaTest
DataJpaTest используется только для теста репозиториев.

Для интеграционного теста лучше использовать `@SpringBootTest`.

2024-06-13 14:46 UTC, sas7289 commented on hw06-jpa/src/main/java/ru/otus/hw/services/BookServiceImpl.java
> +        List<Book> all = bookRepository.findAll();
переименовал

2024-06-13 14:46 UTC, sas7289 commented on hw06-jpa/src/main/java/ru/otus/hw/repositories/JpaBookRepository.java
> +public class JpaBookRepository implements BookRepository {
добавил тесты

2024-06-13 14:47 UTC, sas7289 commented on hw06-jpa/src/main/java/ru/otus/hw/repositories/JpaCommentRepository.java
> +public class JpaCommentRepository implements CommentRepository {
добавил тесты

2024-06-13 14:47 UTC, sas7289 commented on hw06-jpa/src/test/java/ru/otus/hw/repositories/JdbcGenreRepositoryTest.java
> +class JdbcGenreRepositoryTest {
переименовал

2024-06-13 14:47 UTC, sas7289 commented on hw06-jpa/src/test/java/ru/otus/hw/services/BookServiceImplTest.java
> +@DataJpaTest
заменил анотацию

2024-06-13 14:47 UTC, sas7289 commented on hw06-jpa/src/test/java/ru/otus/hw/services/CommentServiceImplTest.java
> +@DataJpaTest
заменил анотацию

2024-06-17 14:11 UTC, VladimirMagerov approved these changes

2024-06-17 14:57 UTC, merged